apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    owner: jay
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
